import json
import os
import boto3

# ==========================================
# CONFIGURATION & PLACEHOLDERS
# ==========================================
# Tip: In AWS Lambda, it's best practice to use Environment Variables or IAM Roles 
# instead of hardcoding credentials. But you can replace these placeholders for local testing.

AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "<YOUR_AWS_ACCESS_KEY_ID>")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "<YOUR_AWS_SECRET_ACCESS_KEY>")
AWS_REGION = os.environ.get("AWS_REGION", "<YOUR_AWS_REGION_E_G_us-east-1>")

TARGET_S3_BUCKET = os.environ.get("TARGET_S3_BUCKET", "<YOUR_S3_BUCKET_NAME>")

# Initialize clients (e.g., S3) using the credentials
s3_client = boto3.client(
    's3',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=AWS_REGION
)

def lambda_handler(event, context):
    """
    Lambda function 2: S3 Processor Example
    Modify this function based on your specific architecture needs.
    """
    try:
        # Example: Process an S3 trigger or perform an S3 action
        # TODO: Add your custom logic here (e.g., reading/writing files to S3)
        
        file_key = "example-file.txt"
        file_content = "Generated by Lambda 2"
        
        # Uploading to S3 as an example
        s3_client.put_object(
            Bucket=TARGET_S3_BUCKET,
            Key=file_key,
            Body=file_content
        )
        
        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': f'Successfully wrote to {TARGET_S3_BUCKET}/{file_key}'
            })
        }
        
    except Exception as e:
        return {
            'statusCode': 500,
            'body': json.dumps({'error': str(e)})
        }
