const { S3Client, PutObjectCommand } = require("@aws-sdk/client-s3");

// ==========================================
// CONFIGURATION & PLACEHOLDERS
// ==========================================
const AWS_REGION = process.env.AWS_REGION || "<YOUR_AWS_REGION_E_G_us-east-1>";
const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID || "<YOUR_AWS_ACCESS_KEY_ID>";
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY || "<YOUR_AWS_SECRET_ACCESS_KEY>";

const TARGET_S3_BUCKET = process.env.TARGET_S3_BUCKET || "<YOUR_S3_BUCKET_NAME>";

// Initialize AWS S3 Client (AWS SDK v3)
const s3Client = new S3Client({
    region: AWS_REGION,
    credentials: {
        accessKeyId: AWS_ACCESS_KEY_ID,
        secretAccessKey: AWS_SECRET_ACCESS_KEY,
    }
});

exports.handler = async (event) => {
    console.log("Incoming event:", JSON.stringify(event, null, 2));

    try {
        // TODO: Add your custom S3 processing logic here
        const fileKey = `output-${Date.now()}.txt`;
        const fileContent = "Generated by Node.js Lambda 2";

        // Example: Uploading a file to the configured S3 bucket
        const command = new PutObjectCommand({
            Bucket: TARGET_S3_BUCKET,
            Key: fileKey,
            Body: fileContent,
            ContentType: "text/plain"
        });

        await s3Client.send(command);

        return {
            statusCode: 200,
            body: JSON.stringify({
                message: `Successfully wrote file to s3://${TARGET_S3_BUCKET}/${fileKey}`
            })
        };
    } catch (error) {
        console.error("Error processing S3 task:", error);
        return {
            statusCode: 500,
            body: JSON.stringify({ error: error.message })
        };
    }
};
